name: footnote
description: Distraction-free research reader for astronomy.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State management / Architecture
  provider: ^6.1.1
  
  # Networking
  http: ^1.2.0
  
  # UI/UX components
  google_fonts: ^6.1.0
  url_launcher: ^6.2.4
  share_plus: ^9.0.0
  intl: ^0.19.0
  
  # Utility
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
